from __future__ import annotations

import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "code"))

from b4_core.native_parsers import (  # noqa: E402
    ModelOutputError,
    parse_native_output,
    parse_prompt_json,
    validate_tool_calls,
)


TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "calculator",
            "description": "Calculate.",
            "parameters": {
                "type": "object",
                "properties": {"expression": {"type": "string"}},
                "required": ["expression"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "file_reader",
            "description": "Read.",
            "parameters": {
                "type": "object",
                "properties": {
                    "path": {"type": "string"},
                    "max_chars": {"type": "integer"},
                },
                "required": ["path"],
                "additionalProperties": False,
            },
        },
    },
]


class NativeParserTests(unittest.TestCase):
    def test_qwen35_xml_multiple_calls(self) -> None:
        raw = """
<tool_call>
<function=file_reader>
<parameter=path>docs/agent_intro.txt</parameter>
<parameter=max_chars>2000</parameter>
</function>
</tool_call>
<tool_call>
<function=calculator>
<parameter=expression>23 * 17 + 9</parameter>
</function>
</tool_call>
"""
        parsed = parse_native_output(raw, "qwen35_xml", "round_1")
        calls = parsed.ai_message["tool_calls"]
        self.assertEqual([call["name"] for call in calls], ["file_reader", "calculator"])
        self.assertEqual(calls[0]["args"]["max_chars"], 2000)
        self.assertEqual(calls[1]["args"]["expression"], "23 * 17 + 9")
        self.assertNotEqual(calls[0]["id"], calls[1]["id"])

    def test_qwen35_python_style_boolean_is_normalized(self) -> None:
        raw = """
<tool_call>
<function=table_analyzer>
<parameter=path>tables/results.csv</parameter>
<parameter=describe>True</parameter>
</function>
</tool_call>
"""
        parsed = parse_native_output(raw, "qwen35_xml", "table")
        self.assertIs(parsed.ai_message["tool_calls"][0]["args"]["describe"], True)

    def test_qwen3_json_multiple_calls(self) -> None:
        raw = """
<tool_call>
{"name":"file_reader","arguments":{"path":"docs/agent_intro.txt"}}
</tool_call>
<tool_call>
{"name":"calculator","arguments":"{\\"expression\\":\\"2+2\\"}"}
</tool_call>
"""
        parsed = parse_native_output(raw, "qwen3_json", "turn-2")
        self.assertEqual(len(parsed.ai_message["tool_calls"]), 2)
        self.assertEqual(parsed.ai_message["tool_calls"][1]["args"], {"expression": "2+2"})

    def test_native_final_answer_and_thinking(self) -> None:
        parsed = parse_native_output("<think>private</think>\n最终答案", "qwen3_json", "final")
        self.assertEqual(parsed.ai_message["content"], "最终答案")
        self.assertEqual(parsed.reasoning_text, "private")

    def test_native_uses_leading_call_and_ignores_simulated_rollout(self) -> None:
        raw = """
<tool_call>
<function=file_reader>
<parameter=path>docs/agent_intro.txt</parameter>
</function>
</tool_call>
user
<tool_response>{"invented": true}</tool_response>
assistant
This suffix was generated by the model, not by the runtime.
"""
        parsed = parse_native_output(raw, "qwen35_xml", "rollout")
        self.assertEqual(len(parsed.ai_message["tool_calls"]), 1)
        self.assertEqual(parsed.ai_message["tool_calls"][0]["name"], "file_reader")
        self.assertGreater(parsed.candidate["ignored_rollout_suffix_chars"], 0)

    def test_prompt_json_accepts_flat_and_openai_calls(self) -> None:
        flat = parse_prompt_json(
            '{"content":"","tool_calls":[{"name":"calculator","args":{"expression":"2+2"}}]}',
            "flat",
        )
        canonical = parse_prompt_json(
            '{"content":"","tool_calls":[{"type":"function","function":{"name":"calculator",'
            '"arguments":{"expression":"2+2"}}}]}',
            "canonical",
        )
        inline = parse_prompt_json(
            '{"content":"","tool_calls":[{"name":"calculator","expression":"2+2"}]}',
            "inline",
        )
        self.assertEqual(flat.ai_message["tool_calls"][0]["args"], canonical.ai_message["tool_calls"][0]["args"])
        self.assertEqual(inline.ai_message["tool_calls"][0]["args"], {"expression": "2+2"})

    def test_prompt_json_rejects_content_and_calls_together(self) -> None:
        with self.assertRaises(ModelOutputError):
            parse_prompt_json(
                '{"content":"answer","tool_calls":[{"name":"calculator","args":{"expression":"2+2"}}]}',
                "bad",
            )

    def test_schema_validation_is_reported_separately(self) -> None:
        valid = validate_tool_calls(
            [{"name": "calculator", "args": {"expression": "2+2"}}],
            TOOLS,
        )
        invalid = validate_tool_calls(
            [{"name": "file_reader", "args": {"path": "x", "max_chars": "many"}}],
            TOOLS,
        )
        self.assertTrue(valid["valid"])
        self.assertFalse(invalid["valid"])
        self.assertIn("must be integer", invalid["errors"][0]["message"])


if __name__ == "__main__":
    unittest.main()
